### ISSUE TITLE
joinData 전역 issue

### ISSUE THREAD

**Issue by SEOKKAMONI** [Bamdoliro/Stupetition-client-V2#14]
> joinData recoil을 왜 전역으로 뻇냐고 물어보시는것같은ㄷ 뺀 이유는 제일 큰 이유는 아이디와 비밀번호 등을 입력하고 회원가입 > 학교 찾기 로 가서 다시 돌아오면 리셋이 되는것을 방지하기 위해 joinData를 전역으로 뺏습니다

joinData를 전역으로 관리하는 건 좀 엥? 스럽네여...
차라리 배갠드 선생님께 학교 설정을 API 분리해달라고 하는 게 나을 거 같아요

_Originally posted by @gimhanul in https://github.com/Bamdoliro/Stupetition-client-V2/issues/13#issuecomment-1420790404_

**Comment by gimhanul** [comment]
api 분리해놨읍니다
DB까지 엎고 다시하세염~~

**Comment by SEOKKAMONI** [comment]
우와....!!!!!!11 감사합니다 바쁘실텐데..ㅠ
